version: "2.4"
services:
  remote-cli:
    image: anylogco/remote-cli:latest
    env_file:
      - envs/anylog_tools.env
    container_name: remote-cli
    stdin_open: true
    tty: true
    network_mode: "host"
    volumes:
      - remote-cli:/app/Remote-CLI/anylog_query/static/json
  anylog-gui:
    image: anylogco/anylog-gui:latest
    container_name: anylog-gui
    network_mode: "host" 
    env_file:
      - envs/anylog_tools.env
    stdin_open: true
    tty: true
    volumes:
      - anylog-gui:/app/AnyLog-GUI/views
volumes:
  remote-cli:
  anylog-gui:
