apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f /home/anylog/deployments/docker-compose/docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: anylog-node
  name: anylog-node
spec:
  ports:
    - name: "32048"
      port: 32048
      targetPort: 32048
    - name: "32049"
      port: 32049
      targetPort: 32049
    - name: "32050"
      port: 32050
      targetPort: 32050
  selector:
    io.kompose.service: anylog-node
status:
  loadBalancer: {}
