apiVersion: v1
data:
  ANYLOG_BROKER_PORT: "32050"
  ANYLOG_REST_PORT: "32049"
  ANYLOG_SERVER_PORT: "32048"
  CLUTSER_NAME: aarna-cluster1
  COMPANY_NAME: Aarna
  DB_IP: 127.0.0.1
  DB_PASSWD: demo
  DB_PORT: "5432"
  DB_TYPE: psql
  DB_USER: aarna
  DEFAULT_DBMS: aarna_demo
  ENABLE_PARTITION: "true"
  MASTER_NODE: 127.0.0.1:32048
  MQTT_ENABLE: "false"
  NODE_NAME: aarna-standalone-node
  NODE_TYPE: standalone
  PARTITION_COLUMN: timestamp
  PARTITION_INTERVAL: 15 days
  PARTITION_KEEP: "6"
  PARTITION_SYNC: 1 day
  SYNC_TIME: 30 second
  TABLE_NAME: '*'
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: anylog-node-envs-anylog_node-env
  name: envs-anylog_node-env
