apiVersion: v1
data:
  POSTGRES_HOST_AUTH_METHOD: trust
  POSTGRES_PASSWORD: demo
  POSTGRES_USER: aarna
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: database-envs-postgres-env
  name: envs-postgres-env
