apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f /home/anylog/deployments/docker-compose/docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: remote-cli
  name: remote-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: remote-cli
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f /home/anylog/deployments/docker-compose/docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: remote-cli
    spec:
      containers:
        - env:
            - name: CLI_PORT
              valueFrom:
                configMapKeyRef:
                  key: CLI_PORT
                  name: envs-anylog_tools-env
            - name: CONFIG_FILE
              valueFrom:
                configMapKeyRef:
                  key: CONFIG_FILE
                  name: envs-anylog_tools-env
            - name: CONFIG_FOLDER
              valueFrom:
                configMapKeyRef:
                  key: CONFIG_FOLDER
                  name: envs-anylog_tools-env
            - name: CONN_IP
              valueFrom:
                configMapKeyRef:
                  key: CONN_IP
                  name: envs-anylog_tools-env
            - name: GUI_PORT
              valueFrom:
                configMapKeyRef:
                  key: GUI_PORT
                  name: envs-anylog_tools-env
          image: anylogco/remote-cli:latest
          name: remote-cli
          ports:
            - containerPort: 8000
          resources: {}
          stdin: true
          tty: true
          volumeMounts:
            - mountPath: /app/Remote-CLI/anylog_query/static/json
              name: remote-cli
      restartPolicy: Always
      volumes:
        - name: remote-cli
          persistentVolumeClaim:
            claimName: remote-cli
status: {}
