apiVersion: v1
kind: ConfigMap
metadata:
  name: query-configurations
  labels:
    app: al-nvidia-query
data:
  NODE_TYPE: "query"
  NODE_NAME: "query-node"
  COMPANY_NAME: "Nvidia"
  #EXTERNAL_IP: <EXTERNAL IP>
  #LOCAL_IP: <LOCAL IP>
  ANYLOG_SERVER_PORT: "32348"
  ANYLOG_REST_PORT: "32349"
  MASTER_NODE: "100.115.6.106:32048"
  SYNC_TIME: "30 second"

  # User should update DB_USER credentials
  DB_TYPE: "psql"
  DB_IP: "postgres"
  DB_USER: "admin"
  DB_PASSWD: "demo"
  DB_PORT: "5432"
  DEFAULT_DBMS: "test"

  MQTT_ENABLE: "false"
  DEPLOY_LOCAL_SCRIPT: "false"