apiVersion: v1
kind: ConfigMap
metadata:
  namespace: '{{ .Values.general.namespace }}'
  name: '{{ .Values.general.configmap_name }}'
  labels:
    app: '{{ .Values.general.app_name }}'
data:
  POSTGRES_USER: '{{ .Values.credentials.username }}'
  POSTGRES_PASSWORD: '{{ .Values.credentials.password }}'
  PGDATA: '{{ .Values.volume.mountPath }}'
  PGPORT: '{{ .Values.networking.port }}'
