apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      #imagePullSecrets:
      #- name: imagepullsecret
      containers:
      - name: postgres
        #image: nvcr.io/uazwwnrnci5h/anylog/postgres:14.0-alpine
        image: postgres:14.0-alpine
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: postgres-configuration
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret-configs
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432
          name: postgres
