apiVersion: v1
kind: ConfigMap
metadata:
  name: gui-configuration
  labels:
    app: anylog-gui
data:
  CONN_IP: "0.0.0.0"
  GUI_PORT: "5000"
  CONFIG_FOLDER: "views"
  CONFIG_FILE: "testnet.json"
---
apiVersion: v1
kind: Service
metadata:
  name: anylog-gui
  labels:
    app: anylog-gui
spec:
  ports:
  - port: 5000
    name: anylog-gui
  selector:
    app: anylog-gui
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: anylog-gui
  labels:
    app: anylog-gui
spec:
  serviceName: "anylog-gui"
  replicas: 1
  selector:
    matchLabels:
      app: anylog-gui
  template:
    metadata:
      labels:
        app: anylog-gui
    spec:
      containers:
      - name: anylog-gui
        image: anylogco/anylog-gui:latest
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: cli-configuration
        ports:
          - containerPort: 5000
            name: anylog-gui
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cli-configuration
  labels:
    app: remote-cli
data:
  CONN_IP: "0.0.0.0"
  CLI_PORT: "8000"

---
apiVersion: v1
kind: Service
metadata:
  name: remote-cli
  labels:
    app: remote-cli
spec:
  ports:
  - port: 8000
    name: remote-cli
  selector:
    app: remote-cli
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: remote-cli
  labels:
    app: remote-cli
spec:
  serviceName: "remote-cli"
  replicas: 1
  selector:
    matchLabels:
      app: remote-cli
  template:
    metadata:
      labels:
        app: remote-cli
    spec:
      containers:
      - name: remote-cli
        image: anylogco/remote-cli:latest
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: cli-configuration
        ports:
          - containerPort: 8000
            name: remote-cli