version: "2.2"
services:
  remote-cli:
    image: anylogco/remote-cli:latest
    container_name: remote-cli
    stdin_open: true
    tty: true
    ports:
      - "${CLI_PORT}:${CLI_PORT}"
    environment:
      - CONN_IP=${CONN_IP}
      - CLI_PORT=${CLI_PORT}
    volumes:
      - remote-cli:/app/Remote-CLI/anylog_query/static/json
volumes:
  remote-cli:
