apiVersion: v1
kind: ConfigMap
metadata:
  namespace: '{{ .Values.general.namespace }}'
  name: '{{ .Values.general.configmap_name }}'
  labels:
    app: '{{ .Values.general.app_name }}'
data:
  GRAFANA_ADMIN_USER: '{{ .Values.configs.username }}'
  GRAFANA_ADMIN_PASSWORD: '{{ .Values.configs.password }}'
  GF_AUTH_DISABLE_LOGIN_FORM: '{{ .Values.configs.disable_login_form }}'
  GF_AUTH_ANONYMOUS_ENABLED: '{{ .Values.configs.enable_anonymous }}'
  GF_SECURITY_ALLOW_EMBEDDING: '{{ .Values.configs.enable_embedding }}'
  GF_INSTALL_PLUGINS: {{ join "," .Values.configs.plugins }}