general:
  namespace: default
  app_name: grafana
  deployment_name: grafana-app
  service_name: grafana-svs
  configmap_name: grafana-configs
  replicas: 1
  
image:
  repository: grafana/grafana
  tag: 8.2.6
  pullPolicy: IfNotPresent

networking:
  port_name: grafana-port
  node_port: 31000
  
configs:
  username: admin
  password: admin
  disable_login_form: false
  enable_anonymous: true
  enable_embedding: true

