general:
  namespace: default
  app_name: postgres
  deployment_name: postgres-app
  service_name: postgres-svs
  configmap_name: postgres-configs
  replicas: 1
  
image:
  repository: postgres
  tag: 14.0-alpine
  pullPolicy: IfNotPresent

networking:
  port_name: psql-port
  port: 5432
  
credentials:
  username: admin
  password: demo
