apiVersion: v1
kind: Service
metadata:
  name: anylog-rest
  labels:
    app: anylog-rest
spec:
  type: NodePort
  ports:
  - name: rest-tcp
    port: 32448
    targetPort: 32448
    nodePort: 32448
  - name: rest-rest
    port: 32449
    targetPort: 32449
    nodePort: 32449
  selector:
    app: anylog-rest
