apiVersion: v1
kind: ConfigMap
metadata:
  namespace: '{{ .Values.general.namespace }}'
  name: '{{ .Values.general.configmap_name }}'
  labels:
    app: '{{ .Values.general.app_name }}'
data:
  CONN_IP: '{{ .Values.networking.ip }}'
  CLI_PORT: '{{ .Values.networking.port }}'
