version: "2.2"
services:
  anylog-node:
    image: ${REPOSITORY}:${TAG}
    env_file:
      - ${ENV_FILE}
    container_name: ${CONTAINER_NAME}
    stdin_open: true
    tty: true
    network_mode: "host" 
    volumes:
      - anylog-node-anylog:/app/AnyLog-Network/anylog
      - anylog-node-blockchain:/app/AnyLog-Network/blockchain
      - anylog-node-data:/app/AnyLog-Network/data
      - anylog-node-local-scripts:/app/AnyLog-Network/scripts
volumes:
  anylog-node-anylog:
      external:
        name: ${CONTAINER_NAME}-anylog
  anylog-node-blockchain:
    external:
      name: ${CONTAINER_NAME}-blockchain
  anylog-node-data:
    external:
      name: ${CONTAINER_NAME}-data
  anylog-node-local-scripts:
    external:
      name: ${CONTAINER_NAME}-local-scripts
