apiVersion: v1
kind: ConfigMap
metadata:
  name: operator-configurations
  labels:
    app: anylog-operator
data:
  NODE_TYPE: "operator"
  NODE_NAME: "operator-node1"
  COMPANY_NAME: "Company Name"
  #EXTERNAL_IP: <EXTERNAL IP>
  #LOCAL_IP: <LOCAL IP>
  ANYLOG_SERVER_PORT: "32148"
  ANYLOG_REST_PORT: "32149"
  MASTER_NODE: "100.115.6.106:32048"
  SYNC_TIME: "30 second"

  # An optional parameter for the number of workers threads that process requests which are send to the provided IP and Port.
  TCP_THREAD_POOL: 6
  # Amount of time (in seconds) until REST timesout
  REST_TIMEOUT: 30
  # The number of concurrent threads supporting HTTP requests.
  REST_THREADS: 5
  # Sets the number of threads supporting queries (the default is 3).
  QUERY_POOL: 3

  # User should update DB_USER credentials
  DB_TYPE: "psql"
  DB_IP: "postgres"
  DB_USER: "admin"
  DB_PORT: "5432"
  DEFAULT_DBMS: "test"

  # NEW_CLUSTER -- cluster name
  CLUSTER_NAME: "demo-cluster1"
  TABLE_NAME: "*"
  ENABLE_PARTITION: "true"
  PARTITION_COLUMN: "timestamp"
  PARTITION_INTERVAL: "14 days"
  PARTITION_KEEP: "1"
  ENABLE_DATA_MONITOR: "false"

  MQTT_ENABLE: "true"
  BROKER: "driver.cloudmqtt.com"
  MQTT_PORT: "18785"
  MQTT_USER: "ibglowct"
  MQTT_PASSWORD: "MSY4e009J7ts"
  MQTT_LOG: "false"
  MQTT_TOPIC_NAME: "anylogedgex"
  MQTT_TOPIC_DBMS: "test"
  # original value was "bring [device]" (Random-Integer-Generator01). howerver, due to a PSQL table name limit size is 65 chars, it's manually changeds to: rand_int
  MQTT_TOPIC_TABLE: "rand_data"
  MQTT_COLUMN_TIMESTAMP: "now"
  MQTT_COLUMN_VALUE_TYPE: "float"
  MQTT_COLUMN_VALUE: "bring [readings][][value]"

  DEPLOY_LOCAL_SCRIPT: "false"
---
apiVersion: v1
kind: Secret
metadata:
  name: operator-secret-configurations
  labels:
    app: anylog-operator
data:
  DB_PASSWD: ZGVtbwo= # passwd | base64