apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster2-operator1-configurations
  labels:
    app: anylog-cluster2-operator1
data:
  NODE_TYPE: "operator"
  NODE_NAME: "nvidia-cluster2-operator1"
  COMPANY_NAME: "Nvidia"
  #EXTERNAL_IP: <EXTERNAL IP>
  #LOCAL_IP: <LOCAL IP>
  ANYLOG_SERVER_PORT: "32158"
  ANYLOG_REST_PORT: "32159"
  MASTER_NODE: "100.115.6.90:32048"
  SYNC_TIME: "30 second"

  # An optional parameter for the number of workers threads that process requests which are send to the provided IP and Port.
  TCP_THREAD_POOL: "6"
  # Amount of time (in seconds) until REST timesout
  REST_TIMEOUT: "30"
  # The number of concurrent threads supporting HTTP requests.
  REST_THREADS: "5"
  # Sets the number of threads supporting queries (the default is 3).
  QUERY_POOL: "3"

# User should update DB_USER credentials
  DB_TYPE: "psql"
  DB_IP: "postgres"
  DB_USER: "admin"
  DB_PASSWD: "demo"
  DEFAULT_DBMS: "nvidia"

  # NEW_CLUSTER -- cluster name
  CLUSTER_NAME: "nvidia-cluster2"
  TABLE_NAME: "*"
  ENABLE_PARTITION: "true"
  PARTITION_COLUMN: "timestamp"
  PARTITION_INTERVAL: "14 days"
  PARTITION_KEEP: "1"
  ENABLE_DATA_MONITOR: "false"

  MQTT_ENABLE: "true"
  BROKER: "driver.cloudmqtt.com"
  MQTT_PORT: "18785"
  MQTT_USER: "ibglowct"
  MQTT_PASSWORD: "MSY4e009J7ts"
  MQTT_LOG: "false"
  MQTT_TOPIC_NAME: "anylogedgex"
  MQTT_TOPIC_DBMS: "nvidia"
  # original value was "bring [device]" (Random-Integer-Generator01). howerver, due to a PSQL table name limit size is 65 chars, it's manually changeds to: rand_int
  MQTT_TOPIC_TABLE: "rand_data"
  MQTT_COLUMN_TIMESTAMP: "now"
  MQTT_COLUMN_VALUE_TYPE: "float"
  MQTT_COLUMN_VALUE: "bring [readings][][value]"

  DEPLOY_LOCAL_SCRIPT: "false"
