apiVersion: v1
kind: Service
metadata:
  name: anylog-operator
  labels:
    app: anylog-operator
spec:
  type: NodePort
  ports:
  - name: anylog-operator-tcp
    port: 32158
    targetPort: 32158
    nodePort: 32158
  - name: anylog-operator-rest
    port: 32159
    targetPort: 32159
    nodePort: 32159
  selector:
    app: anylog-operator