apiVersion: apps/v1
kind: Deployment
metadata:
  name: anylog-query2
  labels:
    app: anylog-query2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anylog-query2
  template:
    metadata:
      labels:
        app: anylog-query2
    spec:
      imagePullSecrets:
      - name: imagepullsecret2
      containers:
      - name: anylog-query2
        image: nvcr.io/uazwwnrnci5h/anylog/anylog-network:predevelop
        #image: anylogco/anylog-network:test 
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: query2-configurations
        ports:
          - containerPort: 32358
            name: query2-tcp
          - containerPort: 32359
            name: query2-rest
